# Generated by Django 4.2.6 on 2023-10-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="media",
            field=models.FileField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
