# Generated by Django 5.0 on 2023-12-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_post_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="privacy",
            field=models.IntegerField(
                choices=[(1, "Public"), (2, "Followers"), (3, "Private")], default=1
            ),
        ),
    ]
