# Generated by Django 5.0 on 2024-01-16 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_post_privacy"),
        ("users", "0002_userprofile_friends_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post",
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="comments",
            field=models.ManyToManyField(
                blank=True,
                related_name="post_comment",
                through="posts.PostComment",
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="post_like",
                through="posts.PostLike",
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="postcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.userprofile"
            ),
        ),
    ]
